name: Run xUnit Playwright Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FUNDA_USER_AGENT: ${{ secrets.FUNDA_USER_AGENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Install Playwright Browsers
        run: pwsh bin/Debug/net*/playwright.ps1 install

      - name: Run xUnit tests
        run: dotnet test --logger:"console;verbosity=detailed" --results-directory ./allure-results

      - name: Install Allure CLI
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report

      - name: Copy Allure report into repo folder
        run: |
          mkdir -p TestReports/Allure
          cp -r allure-report/* TestReports/Allure/

      - name: Commit Allure report to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add TestReports/Allure
          git commit -m "Update Allure report [skip ci]" || echo "No changes to commit"
          git push
