name: Run xUnit Playwright Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FUNDA_USER_AGENT: ${{ secrets.FUNDA_USER_AGENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Adjust if needed

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Install Playwright Browsers
        run: pwsh bin/Debug/net*/playwright.ps1 install

      - name: Run xUnit tests
        run: dotnet test --logger:"console;verbosity=detailed" --results-directory ./allure-results

      - name: Install Allure CLI
        uses: simple-elf/allure-install-action@v1

      - name: Generate Allure Report
        run: |
          allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report
